import { defineStore } from "pinia";

export const useCartStore = defineStore("cartStore", {
  state: () => ({
    items: [
      {
        name: "Поло",
        secondName: "(Ебаная)",
        price: "22.000₸",
        oldPrice: "25.000₸",
        colors: ["#000", "#4e3030", "#fff"],
        img: "/images/products/man/top/robe-WH/robe-wh-asian-1.jpg",
      },
      {
        name: "Поло",
        secondName: "(Ебаная)",
        price: "22.000₸",
        oldPrice: "25.000₸",
        colors: ["#000", "#4e3030", "#fff"],
        img: "/images/products/man/top/robe-WH/robe-wh-asian-1.jpg",
      },
      {
        name: "Поло",
        secondName: "(Ебаная)",
        price: "22.000₸",
        oldPrice: "25.000₸",
        colors: ["#000", "#4e3030", "#fff"],
        img: "/images/products/man/top/robe-WH/robe-wh-asian-1.jpg",
      },
      {
        name: "Поло",
        secondName: "(Ебаная)",
        price: "22.000₸",
        oldPrice: "25.000₸",
        colors: ["#000", "#4e3030", "#fff"],
        img: "/images/products/man/top/robe-WH/robe-wh-asian-1.jpg",
      },
      {
        name: "Поло",
        secondName: "(Ебаная)",
        price: "22.000₸",
        oldPrice: "25.000₸",
        colors: ["#000", "#4e3030", "#fff"],
        img: "/images/products/man/top/robe-WH/robe-wh-asian-1.jpg",
      },
      {
        name: "Поло",
        secondName: "(Ебаная)",
        price: "22.000₸",
        oldPrice: "25.000₸",
        colors: ["#000", "#4e3030", "#fff"],
        img: "/images/products/man/top/robe-WH/robe-wh-asian-1.jpg",
      },
      {
        name: "Поло",
        secondName: "(Ебаная)",
        price: "22.000₸",
        oldPrice: "25.000₸",
        colors: ["#000", "#4e3030", "#fff"],
        img: "/images/products/man/top/robe-WH/robe-wh-asian-1.jpg",
      },
      {
        name: "Поло",
        secondName: "(Ебаная)",
        price: "22.000₸",
        oldPrice: "25.000₸",
        colors: ["#000", "#4e3030", "#fff"],
        img: "/images/products/man/top/robe-WH/robe-wh-asian-1.jpg",
      },
      {
        name: "Поло",
        secondName: "(Ебаная)",
        price: "22.000₸",
        oldPrice: "25.000₸",
        colors: ["#000", "#4e3030", "#fff"],
        img: "/images/products/man/top/robe-WH/robe-wh-asian-1.jpg",
      },
      {
        name: "Поло",
        secondName: "(Ебаная)",
        price: "22.000₸",
        oldPrice: "25.000₸",
        colors: ["#000", "#4e3030", "#fff"],
        img: "/images/products/man/top/robe-WH/robe-wh-asian-1.jpg",
      },
      {
        name: "Поло",
        secondName: "(Ебаная)",
        price: "22.000₸",
        oldPrice: "25.000₸",
        colors: ["#000", "#4e3030", "#fff"],
        img: "/images/products/man/top/robe-WH/robe-wh-asian-1.jpg",
      },
    ],
  }),
});
